name: "Test Dispatch"
on: 
  workflow_dispatch:

jobs:
    build-and-deploy:
      name: Setup, Build and Publish
      runs-on: ubuntu-latest
      steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: "Verify Build"
        working-directory: <MAVEN_BUILD_DIR>
        run: |
          mvn --batch-mode --update-snapshots test 
      - name: Bump version and push tag
        id: tag_version
        if: github.ref == 'refs/heads/master'
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Don't run
        if: github.ref == 'refs/heads/develop'
        run:
          echo "ahhh"
