name: "Test Dispatch"
on: 
  workflow_dispatch:

jobs:
    build-and-deploy:
      name: Setup, Build and Publish
      runs-on: ubuntu-latest
      steps:
      # checkout the repo
      - name: Update Secret
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'TEST_SECRET'
          value: 'Lorem ipsun dolor simit'
          repository: hmanzur/actions-set-secret
          token: ${{ secrets.UPDATE_TOKEN }}
      - name: Print Secret
        run: |
          echo ${{ secrets.TEST_SECRET }}
